version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: edos-postgres
    environment:
      POSTGRES_DB: edos_db
      POSTGRES_USER: edos_user
      POSTGRES_PASSWORD: edos_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - edos-network

  kafka:
    image: apache/kafka:latest
    container_name: edos-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_STORAGE_TOOL: /opt/kafka/bin/kafka-storage.sh
      KAFKA_STORAGE_FORMAT: /opt/kafka/bin/kafka-storage.sh format -t $(KAFKA_CLUSTER_ID) -c /opt/kafka/config/kraft/server.properties
      KAFKA_CLUSTER_ID: "Mk3UO4ZTRaC8h5L6o9M7Rw"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - edos-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: edos-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - edos-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: edos-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - edos-network
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  postgres_data:
    driver: local
  kafka_data:
    driver: local

networks:
  edos-network:
    driver: bridge